---
steps:
- name: hashicorp/terraform
  dir: deployments/app1/dev
  args:
  - init
- name: hashicorp/terraform
  dir: deployments/app1/dev
  args:
  - plan
  - -out=terraform.tfplan
- name: hashicorp/terraform
  dir: deployments/app1/dev
  args:
  - version
- name: gcr.io/config-validator/terraform-validator
  dir: deployments/app1/dev
  args:
  - convert
  - --tf-version
  - "0.11"
  - terraform.json
- name: gcr.io/config-validator/terraform-validator
  dir: deployments/app1/dev
  args:
  - validate
  - terraform.tfplan
  - --policy-path=../../../policy-library/
