---
steps:
- name: hashicorp/terraform
  dir: deployments/app1/dev
  args:
  - init
- name: hashicorp/terraform
  dir: deployments/app1/dev
  args:
  - plan
  - -out=terraform.tfplan
- name: gcr.io/cf-gcp-challenge-dev/terraform-validator
  dir: deployments/app1/dev
  args:
  - convert
  - terraform.tfplan
  - tf-version 0.12
- name: gcr.io/cf-gcp-challenge-dev/terraform-validator
  dir: deployments/app1/dev
  args:
  - validate
  - terraform.tfplan
  -  --policy-path=../../../policy-library/
