---
steps:
- name: hashicorp/terraform
  dir: deployments/app1/dev
  args:
  - init
- name: hashicorp/terraform
  dir: deployments/app1/dev
  args:
  - plan
  - -out=terraform.plan
- name: hashicorp/terraform
  dir: deployments/app1/dev
  args:
  - show 
  - "-json terraform.plan"
  - "> terraform.json"
- name: gcr.io/config-validator/terraform-validator
  dir: deployments/app1/dev
  args:
  - convert
  - --tf-version
  - "0.12"
  - terraform.json
- name: gcr.io/config-validator/terraform-validator
  dir: deployments/app1/dev
  args:
  - validate
  - terraform.json
  - --policy-path=../../../policy-library/
